export enum MessageEnum {
  CREDENTIALS_OK = 'Autenticación Correcta.!',
  CREDENTIALS_INVALID = 'Las credenciales son incorrectas!',
  ACCESS_INVALID = 'El acceso es inválido!',
  PASSWORD_UPDATED = 'Contraseña Actualizada!',
  PASSWORD_RESET = 'Contraseña reseteada!',
  LOGIN_NOT_AUTORIZED = 'No autorizado!!!',

  TOKEN_MODIFIED = 'Token modificado',
  TOKEN_NOT_EXIST = 'Token No Existe!!',
  TOKEN_DELETE = 'Token eliminado correctamente.',

  ENTITY_SELECT = 'Datos devueltos correctamente.',
  ENTITY_ERROR_CREATE = 'Los datos no pudieron ser almacenados correctamente.',
  ENTITY_SELECT_EMPTY = 'No se encontraron registros.',
  ENTITY_PROCESS = 'Datos procesados correctamente.',
  ENTITY_DELETE_SUCCESS = 'Datos eliminados correctamente.',
  ENTITY_ERROR_UPDATE = 'Los datos no pudieron ser actualizados correctamente.',
  ENTITY_ERROR_DELETE = 'Los datos no pudieron ser eliminados correctamente.',

  USER_CREATED = 'Datos del Usuario fueron creados correctamente.',
  USER_UPDATE = 'Datos del Usuario fueron modificados correctamente.',
  USER_DELETE = 'Datos del Usuario fueron eliminados correctamente.',
  USER_EXIST = 'Datos de Usuario ya Existen!',
  USER_NOT_EXIST = 'Datos de Usuario no existen!',
  USER_VALIDATED = 'Datos del Usuario fueron validados correctamente.',
  USER_HAS_NOT_ROLES = 'Usuario no tiene roles asignados!',

  OPERATION_SUCCESS = 'Operación realizada con éxito!',
  OPERATION_FAILED = 'La operación falló!',
  PERMISSION_DENIED = 'Permiso denegado!',
  SERVICE_UNAVAILABLE = 'Servicio no disponible en este momento. Por favor, inténtalo de nuevo más tarde.',
  DATA_CONFLICT = 'Conflicto de datos detectado!',
  DATA_INVALID = 'Datos proporcionados no son válidos!',
  REQUEST_INVALID = 'Solicitud no válida!',
  REQUEST_TIMEOUT = 'La solicitud ha excedido el tiempo de espera!',
  SERVER_ERROR = 'Error interno del servidor!',
  NOT_FOUND = 'El recurso solicitado no fue encontrado!',
  RATE_LIMIT_EXCEEDED = 'Se ha excedido el límite de solicitudes!',
  INVALID_OLD_PASSWORD = 'La contraseña antigua no coincide!',
  ENTITY_ERROR_RETRIEVE = 'Los datos no pudieron ser recuperados correctamente.',

  ROLE_CREATED = 'Datos del Rol fueron creados correctamente.',
  ROLE_UPDATE = 'Datos del Rol fueron modificados correctamente.',
  ROLE_DELETE = 'Datos del Rol fueron eliminados correctamente.',
  ROLE_EXIST = 'Datos de Rol ya Existen!',
  ROLE_NOT_EXIST = 'Datos de Rol no existen!',
  ROLE_VALIDATED = 'Datos del Rol fueron validados correctamente.',

  STUDENT_CREATED = 'Datos del Estudiante fueron creados correctamente.',
  STUDENT_UPDATE = 'Datos del Estudiante fueron modificados correctamente.',
  STUDENT_DELETE = 'Datos del Estudiante fueron eliminados correctamente.',
  STUDENT_EXIST = 'Datos de Estudiante ya Existen!',
  STUDENT_NOT_EXIST = 'Datos de Estudiante no existen!',
  STUDENT_VALIDATED = 'Datos del Estudiante fueron validados correctamente.',

  STUDENT_FRONT_CREATED = 'Datos del Estudiante Front fueron creados correctamente.',
  STUDENT_FRONT_UPDATE = 'Datos del Estudiante Front fueron modificados correctamente.',
  STUDENT_FRONT_DELETE = 'Datos del Estudiante Front fueron eliminados correctamente.',
  STUDENT_FRONT_EXIST = 'Datos de Estudiante Front ya Existen!',
  STUDENT_FRONT_NOT_EXIST = 'Datos de Estudiante Front no existen!',
  STUDENT_FRONT_VALIDATED = 'Datos del Estudiante Front fueron validados correctamente.',
  STUDENT_FRONT_ERROR_RETRIEVE = 'Los datos del Estudiante Front no pudieron ser recuperados correctamente.',
  STUDENT_FRONT_ERROR_CREATE = 'Los datos del Estudiante Front no pudieron ser creados correctamente.',

  PROPOSAL_CREATED = 'Datos de la Propuesta fueron creados correctamente.',
  PROPOSAL_UPDATE = 'Datos de la Propuesta fueron modificados correctamente.',
  PROPOSAL_DELETE = 'Datos de la Propuesta fueron eliminados correctamente.',
  PROPOSAL_EXIST = 'Datos de la Propuesta ya Existen!',
  PROPOSAL_NOT_EXIST = 'Datos de la Propuesta no existen!',
  PROPOSAL_VALIDATED = 'Datos de la Propuesta fueron validados correctamente.',
  PROPOSAL_ERROR_RETRIEVE = 'Los datos de la Propuesta no pudieron ser recuperados correctamente.',
  PROPOSAL_ERROR_CREATE = 'Los datos de la Propuesta no pudieron ser creados correctamente.',
  PROPOSAL_ERROR_UPDATE = 'Los datos de la Propuesta no pudieron ser actualizados correctamente.',
  PROPOSAL_ERROR_DELETE = 'Los datos de la Propuesta no pudieron ser eliminados correctamente.',

  CAREER_CREATED = 'Datos de la Carrera fueron creados correctamente.',
  CAREER_UPDATE = 'Datos de la Carrera fueron modificados correctamente.',
  CAREER_DELETE = 'Datos de la Carrera fueron eliminados correctamente.',
  CAREER_EXIST = 'Datos de la Carrera ya Existen!',
  CAREER_NOT_EXIST = 'Datos de la Carrera no existen!',
  CAREER_VALIDATED = 'Datos de la Carrera fueron validados correctamente.',
  CAREER_ERROR_RETRIEVE = 'Los datos de la Carrera no pudieron ser recuperados correctamente.',
  CAREER_ERROR_CREATE = 'Los datos de la Carrera no pudieron ser creados correctamente.',
  CAREER_ERROR_UPDATE = 'Los datos de la Carrera no pudieron ser actualizados correctamente.',
  CAREER_ERROR_DELETE = 'Los datos de la Carrera no pudieron ser eliminados correctamente.',

  INVALID_ROLE = 'Rol inválido',
}
